### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported in Swift 4.1.50

### ISSUE THREAD

**Issue by huaijing** [selerio/selerio-arkit-basics#1]
hello,

I try to compile this demo in Xcode(Version 10.0 beta 3 (10L201y)), receiving this error message:

> Module compiled with Swift 4.2 cannot be imported in Swift 4.1.50

**Comment by huaijing** [comment]
I changed the Build Settings of Swift Language Version: Swift 4.2, receiving this error message:

> Module file was created by an older version of the compiler; rebuild 'SelerioARKit' and try again

which version of Xcode did you use？

**Comment by ftasse** [comment]
Hey Jing,
Sorry you are having issues compiling. We are working on a fix right now. To answer your question, we test extensively on Xcode Version 10.0 beta 2, as well as earlier versions of Xcode.

**Comment by ftasse** [comment]
We now use Cocoapods for the SDK distribution  (from commit 62fa4de), which fixes the versioning issues.
